apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 436063288721.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 436063288721.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 72976fa1
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
